# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5cc4a1f30cb4f5b31a8d455b2ec34431db0a098a5f96f6bc9daf978009019ce1dfd25eb4d40097625843b2ac4f2def80de5128738fad67a749aefafe2709c7f

test:
  secret_key_base: a6e8a128acc111bd595445c9565765feefd0fd59bb0cf8a49b898b19eb9e0848adee489228747ef3059d6093d20fdb805a7b52fede61a2d7a95710e5c449447d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
